### PR TITLE
Add french locale

### PR DESCRIPTION
**Pull request by mrintrepide**
English locale translated to French

### CODE REVIEW

**Comment by Tohrusky** [comment]
Could you fix the unit test? It will get merged when the CICD passes properly.

**Comment by mrintrepide** [comment]
> Could you fix the unit test? It will get merged when the CICD passes properly.

I thing I fix missing array content.

**Comment by Tohrusky** [comment]
> > Could you fix the unit test? It will get merged when the CICD passes properly.
> 
> I think I fix missing array content.

add "fr" in https://github.com/Tohrusky/Final2x/blob/main/src/renderer/src/utils/index.ts#L13

**Comment by mrintrepide** [comment]
> > > Could you fix the unit test? It will get merged when the CICD passes properly.
> > 
> > 
> > I think I fix missing array content.
> 
> add "fr" in https://github.com/Tohrusky/Final2x/blob/main/src/renderer/src/utils/index.ts#L13

Need I add for french id (3) here ? `* @param id 语言id 0-> en, 1-> zh, 2-> ja`
I'm not TypeScript dev

**Review by Tohrusky — APPROVED** [review]

**Comment by Tohrusky** [comment]
Thx! I will fix uni test~

**Comment by Tohrusky** [comment]
4b2999ad922100a62fd26dc9e9a4a1af
@mrintrepide The text here goes beyond the border, can you replace it with a shorter expression or change it to English?

**Comment by mrintrepide** [comment]
> 4b2999ad922100a62fd26dc9e9a4a1af @mrintrepide The text here goes beyond the border, can you replace it with a shorter expression or change it to English?

French words are a bit more longer than English. I can truncate/tweak some words.

**Comment by Tohrusky** [comment]
I refactor some code in https://github.com/Tohrusky/Final2x/pull/234.. and run `pnpm run lint` before ya push the code~

**Comment by mrintrepide** [comment]
I make some [truncation](https://github.com/mrintrepide/Final2x/commit/70466be1efae0ca7e3569463890a270584442a88). Need to open a new PR ?

**Comment by Tohrusky** [comment]
> I make some [truncation](https://github.com/mrintrepide/Final2x/commit/70466be1efae0ca7e3569463890a270584442a88). Need to open a new PR ?

Sure! It seems perfect now!

**Comment by Tohrusky** [comment]
you can download the nightly version here, the next version will release after I fixed the issues (
https://github.com/Tohrusky/Final2x/actions/runs/6914977219
https://github.com/Tohrusky/Final2x/actions/workflows/CI-Build.yml

**Comment by mrintrepide** [comment]
> you can download the nightly version here, the next version will release after I fixed the issues
Thanks, seems good with #237
image

**Pull request merged**
